### ISSUE TITLE
Issues for the Relics Mod

### ISSUE THREAD

**Issue by IamRyan30** [AHilyard/LegendaryTooltips#10]
MC version: 1.16.5
Forge version: 36.2.4
Mod version: I've tried with 6 of them
Relics version: relics-0.3.4.jar (I've tried previous versions of this mod, too)

The tooltip is twitching like crazy. I've tried multiple LT and Iceberg versions and none seem to fix the issue.
![image](https://user-images.githubusercontent.com/91336389/150656444-490c5734-e35e-4d24-8c75-13627b55e605.png)

**Comment by AHilyard** [comment]
Hey, thanks for the report.  I've been working with the Relics dev on this to get the bug fixed, and have opened a pull request here: https://github.com/SSKirillSS/relics/pull/57
Once that is merged this should be resolved.

**Comment by AHilyard** [comment]
The PR has been merged, so this issue should be resolved.
