### ISSUE TITLE
[1.20/Fabric] Crash with Andromeda

### ISSUE THREAD

**Issue by melontini** [AHilyard/LegendaryTooltips#101]
Hi, I received multiple crash reports about my mod crashing with Legendary Tooltips installed.

Here's the stacktrace:
https://hastebin.com/share/oqohevakon.php

Deobfuscated:
https://hastebin.com/share/irovexexod.php

This happens when my mod is trying to render [item frame tooltips](https://github.com/melontini/andromeda/blob/f453dbc9be1f3b132f801bd5b28fcdffd979423d/src/main/java/me/melontini/andromeda/client/AndromedaClient.java#L112), which calls the [drawTooltip method when there's no screen open](https://github.com/melontini/dark-matter/blob/a70578a36d111378429dc3734ba2601ccac342bf/dark-matter-minecraft/src/main/java/me/melontini/dark_matter/minecraft/client/util/DrawUtil.java#L79).

**Comment by AHilyard** [comment]
Hey, thanks for letting me know.  I've fixed this in the latest version of Iceberg (1.1.13). 😄

**Comment by AHilyard** [comment]
I'll close this issue now, feel free to reopen if things are not working as expected.

**Comment by HyperGamesDev** [comment]
Dont wana reopen this if it is unrelated but Im pretty sure it is, too bad I cant see the pastebin
I dont know how to explain it, I tried updating all of the Sodium, Indium and Iris mods, which didnt work out well with all the mods I had so I switched back to the older versions Im pretty sure with everything and then I started getting a crash when hovering over a item with the Legendary Tooltips mod
I did also update Andromeda and Iceberg as they were causing issues with itemframed maps
And I dont know what happened now, I modified the config to turn off the 3D renders of items while also rolling back the version of Andromeda which weirdly enough works now (and didnt crash with the map), but yeah it is not the 3D renders, but the newest version of Andromeda? (0.9.1)
[Minecraft modding is so scuffed]

Here's the latest crash report I had
https://pastebin.com/YiyHg8Qz

**Comment by melontini** [comment]
You should open a separate issue, as this is not related to Andromeda. The only mods in the stacktrace are iceberg, sodium and inventorio.

**Comment by HyperGamesDev** [comment]
Ah I see, thank you, will do 
#109 
Well yeah thats the thing, I tried updating the Sodium to newest versions (0.5.1) and other mods including Indium, Iris, Iceberg and Andromeda, but then other things started crashing like Cave Dust, and then I was getting a report I did not know what to do as the only suspected where literally Minecraft and Fabric, didnt detect a cause from a mod and the error was very vague like null exception or something
