### ISSUE TITLE
1.20.1 Latest Release Tooltips isnt working for the latest Forge. 

### ISSUE THREAD

**Issue by ZonedOutMC** [AHilyard/LegendaryTooltips#104]
I keep getting Exit Code: 1 which signifies the mod is outdated, but the mod is a 1.20.1 mod and I'm running forge on 1.20.1. 

Unsure why its doing that, but it keeps crashing due to this.

**Comment by AHilyard** [comment]
I am closing this issue due to its age but please reopen with a crash log if you are still experiencing this problem.
