### ISSUE TITLE
[1.20.1] crash when hovering over the recipe book

### ISSUE THREAD

**Issue by EnderMelody** [AHilyard/LegendaryTooltips#106]
minecraft: 1.20.1
quilt: 0.19.2
sodium: 0.5.0 build 111
iceberg: 1.1.13
hovering over the recipe book freezes the client and crashes. seems to be from the update sodium did recently.

[crash-2023-08-05_12.44.45-client.txt](https://github.com/AHilyard/Iceberg/files/12267690/crash-2023-08-05_12.44.45-client.txt)

**Comment by AHilyard** [comment]
This has been fixed in the latest update to Iceberg.
