### ISSUE TITLE
LegendaryTooltips Partially Overlay on top of Relics borders

### ISSUE THREAD

**Issue by RobertHDPotatoes** [AHilyard/LegendaryTooltips#12]
Issue:
By default when installing LegendaryTooltips, all items in Minecraft classified as having the "Uncommon", "Rare", or "Epic" rarities are granted a default border, respective of their rarity. These default borders overlay partially on top of Relics custom borders, as shown in the attached screenshot. Items like relics:leather_belt are unaffected because that item does not have a rarity, and is not given a border by LegendaryTooltips, but an item like relics:spore_sack will have the "Uncommon" rarity border overlaying on top of Relics border. Players could remove LegendaryTooltips default rarity border entries, but that almost defeats the purpose of having LegendaryTooltips.

Minecraft Version: 1.16.5
Forge Version: 36.2.22
Relics Version: 0.3.4.1
LegendaryTooltips Version: 1.1.5

![image](https://user-images.githubusercontent.com/72235443/152084987-c42ba88b-b64f-4537-8587-fad881b2ff31.png)

**Comment by AHilyard** [comment]
Thanks for the report!  I've added a new "blacklist" configuration option in the latest version of Legendary Tooltips (1.1.6).  You can specify "@relics" as a blacklist entry to ensure this won't happen.  Enjoy. :)

**Comment by RobertHDPotatoes** [comment]
Just tested it out and it works perfectly. I'm happy to see compatibility (in one way or another) between Relics and LegendaryTooltips!
