### ISSUE TITLE
Incompatability with Metal Bundles

### ISSUE THREAD

**Issue by QwertRvg** [AHilyard/LegendaryTooltips#130]
[Forge for v1.20.1]

The mod breaks the tooltip of the Metal Bundles mod. It flashes shortly and then disappears.

Normal UI:
![image](https://github.com/AHilyard/LegendaryTooltips/assets/89683173/3ef68f1e-51c2-498e-87a1-0dcd9a7840dc)

With the mod:
![image](https://github.com/AHilyard/LegendaryTooltips/assets/89683173/3f96dcc8-4f16-455e-bd46-9ad3b56a1ce9)

**Comment by AHilyard** [comment]
Can you verify if this is still happening with the latest versions of Iceberg and Legendary Tooltips?  I've done some testing and I can't reproduce the issues you describe.

![image](https://github.com/AHilyard/LegendaryTooltips/assets/12298785/19b5f408-2127-4fe7-9f5b-4a32095f508e)

**Comment by AHilyard** [comment]
Actually I just noticed you have the 3D item preview enabled with bundles and I can confirm when the preview is turned on I get this behavior as well.  I am working on the fix now.

**Comment by AHilyard** [comment]
Good news, I was able to fix this with an update to Iceberg.  Version 1.1.18 should resolve this for you. :)

**Comment by QwertRvg** [comment]
Wow! Thank you so much!
