### ISSUE TITLE
[1.20.1] [Quilt] When looking at an items tooltip, the NBT data gets modified.

### ISSUE THREAD

**Issue by N0aW** [AHilyard/LegendaryTooltips#133]
Minecraft Version: 1.20.1
Quilt Loader Version: 0.21.2
Mod Version: 1.4.4

When looking at an item's tooltip, the nbt data gets modified.
If in creative mode, the nbt data really gets modified, but in survival mode, it just looks modified, but isn't really. Using the item will reveal the true NBT stat in survival.
Examples:
When looking at a loaded crossbow, it gets unloaded.
When looking at a hammer from [Banilla Hammers](https://github.com/Theoness1/banilla-hammers) the durability gets drained quickly, even going to negatives.
![image](https://github.com/AHilyard/LegendaryTooltips/assets/76262280/40ce2bb5-08dc-4648-a964-d469b334093d)

**Comment by AHilyard** [comment]
I have verified this issue, I'll update once I know more.

**Comment by AHilyard** [comment]
I have fixed this issue in Iceberg version 1.1.18.  Enjoy :)
