### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by LunexSan** [AHilyard/LegendaryTooltips#145]
Hey,
I'm sure it's probably already in the works, but if not, could this get updated to minecraft version 1.21?

**Comment by IdkWhatToCallMe123** [comment]
There is a [1.21 branch](https://github.com/AHilyard/LegendaryTooltips/tree/1.21-fabric) so hopefully we'll see it soon

**Comment by AHilyard** [comment]
Done. 😄
