### ISSUE TITLE
crash with JEI

### ISSUE THREAD

**Issue by ixradioactivexi** [AHilyard/LegendaryTooltips#148]
crash when mouse hovers over items in JEI menu.
[crash-2024-07-29_14.02.59-client.txt](https://github.com/user-attachments/files/16420611/crash-2024-07-29_14.02.59-client.txt)

**Comment by Ryank414** [comment]
I am experiencing this issue as well. The tooltips look great and helps prevent those super wide ones so would love to use this mod. Unfortunately, jei is just too crucial in a modded playthrough to choose tooltips over it.

**Comment by ixradioactivexi** [comment]
newest update fixed it
