### ISSUE TITLE
Jar version metadata not set up correctly

### ISSUE THREAD

**Issue by T3sT3ro** [AHilyard/LegendaryTooltips#15]
This is how mod version is displayed in multimc:
![image](https://user-images.githubusercontent.com/5300963/152796995-8070ab5e-8755-43de-bfa3-7e3e892e6ba0.png)

So it means there is something wrong with `gradle.properties` `build.gradle` or `mods.toml` file.

**Comment by AHilyard** [comment]
Thanks for the heads up, it looks like I put an extra curly brace at the end there, oops!  This will be fixed in the next update.

**Comment by AHilyard** [comment]
@T3sT3ro This has been fixed in the latest release (1.2.4).  Thanks!
