### ISSUE TITLE
[1.16.5] unnecessary log spam

### ISSUE THREAD

**Issue by SteamDoge9000** [AHilyard/LegendaryTooltips#2]
Well, it sseems that this is the first issue here, so I guess I have the liberty of being the fist one to make a issue report on this.

anyway, the issue here is not nessisary a bug, but more of a console log issue, ive noticed that when you hover over items that the game will log it as Item: air or whatever item your hovering over, while this itself is not an issue, it can lead to the log filling up pretty quickly

if you can make it so this docent happen that would be nice, and if its needed, maybe add it as a debug option 

anyhow that is all, love the detail you put into this mod and the others you did as well

**Comment by AHilyard** [comment]
Well that's embarrassing, looks like I missed a debug statement when cleaning up the previous update for release.  I'll get this taken care of in the next update, thanks for the report.

**Comment by AHilyard** [comment]
@SteamDoge9000 Can I get more information about your setup?  I've just looked over Legendary Tooltips 1.1.5 for Minecraft 1.16.5 and I don't see what you are describing.  What version of the mod are you using, what Minecraft version, and what modloader?

**Comment by SteamDoge9000** [comment]
Forge ver 36.2.22

That's all I can assess rn, I'll provide you a crashlog (f3+c method) to generate the system specs

As for the issue, it only logs it in the game log when you hover over an item

**Comment by AHilyard** [comment]
This was an issue in Iceberg, and has been fixed with the latest release (1.0.38), [here](https://www.curseforge.com/minecraft/mc-mods/iceberg/files/3609064).
