### ISSUE TITLE
Crash in the controls menu

### ISSUE THREAD

**Issue by IamRyan30** [AHilyard/LegendaryTooltips#20]
MC: 1.16.5
Forge: 36.2.21
Mod version: LegendaryTooltips-1.16.5-1.1.6.jar
Iceberg Version: Iceberg-1.16.5-1.0.38.jar

While I'm in the controls menu and I press the `shift` key, the game crashes. Issue was fixed after removing Legendary Tooltips and Iceberg. [Here](https://gist.github.com/IamRyan30/0ed55d90ad2bfe4d745e027f82919f96)'s the log file and [here](https://gist.github.com/IamRyan30/56640eabd5ec55c44eec91cc6a7c1658)'s the mod list.

**Comment by AHilyard** [comment]
Thank you for the report, this has been fixed in [version 1.0.41 of Iceberg ](https://www.curseforge.com/minecraft/mc-mods/iceberg/files/3788411).
