### ISSUE TITLE
Incompatibility????

### ISSUE THREAD

**Issue by lSherozl** [AHilyard/LegendaryTooltips#25]
I can not read this error report, all I know is 2 mods are mentioned one is legendary tips and the other is chaos awakens, when I go to click options in the main menu of Minecraft, game crashes. This is using Occulus with Rubidium to get shaders. Going into a world and using options there is fine, just not on the main menu. 
[crash-2022-05-30_20.32.57-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/8802244/crash-2022-05-30_20.32.57-client.txt)
 
Update: Removing Legendary Tooltips fixes the issue, I believe its an incompatibility with chaos awakens and Legendary Tooltips

**Comment by AHilyard** [comment]
This issue has been fixed in Iceberg version 1.0.41.  Updating to this version should allow you to use Legendary Tooltips with Chaos Awakens.
