### ISSUE TITLE
[Relative Issue Investigation Request] Concurrent Modification Exception crash when loading new resources on Parry This!

### ISSUE THREAD

**Issue by Kaleidio** [AHilyard/LegendaryTooltips#27]
Crash reports on another mod that builds its own tooltips, Parry This!, state a concurrent modification exception building tooltips that refer to its provided tags.  Your mod is among other custom tooltip mods that crash in this fashion.  I feel parry this is the core of the issue, such as not registering tags before renderers, but your mod is involved so I felt it best to include this here.

https://github.com/theishiopian/Parrying/issues/21

**Comment by Kaleidio** [comment]
I can confirm it is an incompatibility with your legendary tooltips mod.

**Comment by AHilyard** [comment]
I couldn't find any incompatibilities with Legendary Tooltips or Iceberg.  I have however created a PR in Parry This that fixes this issue.
