### ISSUE TITLE
[1.18.2] Noticed that items from Enigmatic Legacy don't have the divider line or centered names

### ISSUE THREAD

**Issue by vizthex123** [AHilyard/LegendaryTooltips#29]
Seems to apply to every item in the mod, like you can see below
![image](https://user-images.githubusercontent.com/31721920/177020010-c97ef835-02de-4921-9196-df1a2d428d59.png)
![image](https://user-images.githubusercontent.com/31721920/177020016-bd4335b6-bca6-4e28-9165-4bb4ad510c2a.png)

The item names also aren't centered
![image](https://user-images.githubusercontent.com/31721920/177020023-e2fb8f9a-e159-4d08-a90d-9d2aa03a4e3e.png)
![image](https://user-images.githubusercontent.com/31721920/177020028-efac4aa0-b7d3-4867-b454-cd894f181f62.png)

**Comment by AHilyard** [comment]
If it only affects one mod, that mod is likely building the tooltips in a non-standard way so the onus would be on that mod's author.  I will look into it to verify and get back to you.

**Comment by vizthex123** [comment]
Alright then, guess I can tell them about it.

**Comment by Blugori** [comment]
Similar issue with the mod apotheosis : 
When I combine a gem with an item, things get weird, and I assume it's an incompatibility between legendary tooltips and apotheosis : 
![1](https://user-images.githubusercontent.com/66573974/189503268-382fd644-0264-4d76-acae-ed12b3657a03.png)
![2](https://user-images.githubusercontent.com/66573974/189503269-5d52862d-40d7-4d2d-b285-638ac9358080.png)

**Comment by Blugori** [comment]
more visible issue : 
![image](https://user-images.githubusercontent.com/66573974/189503532-76b2bf04-00eb-4d5f-a491-eb7360e3de2b.png)

**Comment by TheFurryDevil** [comment]
Looks like Apotheosis forgot to revert the scale

**Comment by AHilyard** [comment]
> Looks like Apotheosis forgot to revert the scale. Edit: I don't know. [SocketTooltipRenderer](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/adventure/client/SocketTooltipRenderer.java#L62) Just leaving this here in case

Sorry I haven't updated this issue, but I'm not really sure what you mean in your post.  See the commit history on the file you have linked (https://github.com/Shadows-of-Fire/Apotheosis/commit/2624034d1ac2fe154c1bb2f68dfddf9343471a86), I fixed the issue that was preventing the divider line from appearing among other problems.

**Comment by TheFurryDevil** [comment]
> > Looks like Apotheosis forgot to revert the scale. Edit: I don't know. [SocketTooltipRenderer](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/adventure/client/SocketTooltipRenderer.java#L62) Just leaving this here in case
> 
> Sorry I haven't updated this issue, but I'm not really sure what you mean in your post. See the commit history on the file you have linked ([Shadows-of-Fire/Apotheosis@2624034](https://github.com/Shadows-of-Fire/Apotheosis/commit/2624034d1ac2fe154c1bb2f68dfddf9343471a86)), I fixed the issue that was preventing the divider line from appearing among other problems.

When I tried Apotheosis and Legendary Tooltips together as soon as there is a gem socketed in an item it breaks the border decorations of Legendary Tooltips (and also the 'Add...' button of REI). That's the issue @Blugori showed.

I merely chimed in and looked through the source to find how Apotheosis renders sockets and gems... Sorry lol
