### ISSUE TITLE
[1.18.1] Server crash

### ISSUE THREAD

**Issue by Charismara** [AHilyard/LegendaryTooltips#3]
The Server crashes when starting with LegendaryTooltips
Crash Report: https://mcpaste.io/e1a188f3a7a3dd46

**Comment by AHilyard** [comment]
Legendary Tooltips is a client-side only mod, it doesn't need to be installed on the server.

**Comment by satoon10** [comment]
Then how am I supposed to play it on single player?

**Comment by satoon10** [comment]
The crash still hapens

**Comment by Charismara** [comment]
> The crash still hapens

@AHilyard hasn't merged by Fix and hasn't fixed it on his own so... it'll remain until the Mod is dead
