### ISSUE TITLE
Broken on newest versions of forge 1.19. Should be an easy fix.

### ISSUE THREAD

**Issue by chris-wjn** [AHilyard/LegendaryTooltips#32]
On the newest versions of Forge, GuiUtils has been renamed to ScreenUtils. I briefly looked through your class that uses GuiUtils and it seems like the new version of the class has all the same methods, but I could've missed something.

**Comment by Spittys** [comment]
Custom borders aren't working for me, either.

**Comment by AHilyard** [comment]
Thanks for the report, you are correct that this was broken in a recent version of Forge.  This has been fixed in version 1.3 of Legendary Tooltips available on CurseForge now. 😄
