### ISSUE TITLE
1.12 version lists iceberg as dependency, autoinstalls, iceberg crashes because it has no 1.12 version

### ISSUE THREAD

**Issue by IceArcher937** [AHilyard/LegendaryTooltips#34]
In 1.12.2, when you install this mod on curseforge it will autoinstall the 1.16 version of iceberg because it's listed as a required dependency/library mod, but then it crashes because it's a 1.16 mod:)
I have logs if ya want em

**Comment by AHilyard** [comment]
Thanks for letting me know, this was likely an issue of CurseForge automatically assigning dependencies.  I've removed Iceberg as a dependency for the latest 1.12 release.  As of writing this, the CurseForge app is still automatically adding Iceberg when adding Legendary Tooltips, but I'm hoping within 24-48 hours they fix it.  I'll close this issue but please reopen if it's still broken after a few days.
On a related note, it's really strange behavior that CurseForge installs a dependency version that it knows is wrong, I'll bring it up with support and see what they say.
