### ISSUE TITLE
crashes on hover (1.19)

### ISSUE THREAD

**Issue by cypressfalls** [AHilyard/LegendaryTooltips#36]
when going in the inventory, hovering over any item with a custom tooltip immediately crashes the game. crashes are fixed when taking legendary tooltips out.
[crash-2022-09-02_13.53.07-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/9480393/crash-2022-09-02_13.53.07-client.txt)

**Comment by AHilyard** [comment]
This has already been fixed.  Update Legendary Tooltips to the latest version as well as Forge.
