### ISSUE TITLE
type COMMON for modid legendarytooltips

### ISSUE THREAD

**Issue by shadowsoul8000** [AHilyard/LegendaryTooltips#37]
![Screenshot 2022-09-06 233912](https://user-images.githubusercontent.com/51221645/188806711-a28217aa-5a1c-4962-8568-4c36616f554a.png)
The game crashes when I try to target "$spartanweaponry:netherite_weapons", everything runs fine until I added this, I've tried typing COMMON just about everythere in the config.

**Comment by AHilyard** [comment]
Please upload your config file so I can take a look.  Also, I don't understand why you would type COMMON anywhere, what do you mean?

**Comment by shadowsoul8000** [comment]
The error code said to type COMMON, I assumed that meant in the config file.
[legendarytooltips-common.txt](https://github.com/AHilyard/LegendaryTooltips/files/9503433/legendarytooltips-common.txt)

**Comment by AHilyard** [comment]
I think you've misread, the error says "Failed loading config file legendarytooltips-common.toml of type COMMON for modid legendarytooltips".  I'm not seeing any obvious problems in the config file, could you upload your latest.log file from when this error happened?

**Comment by shadowsoul8000** [comment]
Just tried running the game again and all my configs are working, it recognizes the spartanweaponry tags and everything, maybe it just needed my pc to restart. Thanks for helping. (and yeah looking back on the error log I was reading it like a dumbass)
![2022-09-07_10 55 56](https://user-images.githubusercontent.com/51221645/188946559-c3a6cc19-1d4c-4e14-a2ad-39980eeafa21.png)

**Comment by AHilyard** [comment]
Awesome, I'm glad it's working now, hopefully it doesn't crash again but if it does feel free to reopen this issue with your log file.  Also, that error message you got is very poorly worded so it's understandable how it could be misread, no failure on your part.
