### ISSUE TITLE
Bug with apotheosis mod, the legendary tooltip overlay doesnt render at the good place

### ISSUE THREAD

**Issue by Blugori** [AHilyard/LegendaryTooltips#38]
I encountered this issue while playing with items from apotheosis, I asked them if they could fix it, but they told me it might be on your end :3 
It looks like this in game : 

![3](https://user-images.githubusercontent.com/66573974/189876288-ef21532f-f886-40db-b936-3b8557f4b267.png)

Thanks for reading !

**Comment by AHilyard** [comment]
Interesting, I will look into this and let you know what I find.

**Comment by AHilyard** [comment]
I've submitted a PR that will fix this bug, thanks for bringing it to my attention.  I will close this issue, hopefully the fix will be released shortly. 😄
