### ISSUE TITLE
Fabric 1.19.2 Issue

### ISSUE THREAD

**Issue by AzureDoom** [AHilyard/LegendaryTooltips#39]
Mod Version: 1.3.3
Fabric Version: 0.14.9
Fabric API Version: 0.61.0
Prism Version: 1.0.1
Iceberg Version: 1.0.46
Forge Config API Port: 4.2.6

Issue: 
```
[22:28:22] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.ClassCastException: class net.minecraft.class_5251 cannot be cast to class com.anthonyhilyard.prism.util.IColor (net.minecraft.class_5251 and com.anthonyhilyard.prism.util.IColor are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @21a947fe)
```

Reverting to 1.2.6 allows the to launch correctly.

**Comment by AHilyard** [comment]
Could you please post your latest.log from when this crash occurred?  It contains some more context that will be helpful tracking this issue down.

**Comment by AzureDoom** [comment]
Yup, https://gist.github.com/AzureDoom/b21dbfbbcc06b646c354e6cfbb835067#file-gistfile1-txt-L1102

Will just set there and loop until I kill the game.

**Comment by AHilyard** [comment]
Very strange, it's taken me a while to track it down but there appears to be an incompatibility with the Vein Mining mod.  I am debugging to determine exactly why, but this mod is preventing one of Prism's mixins from applying which is causing the crash.  I will let you know when I know more.

**Comment by AHilyard** [comment]
I've reported this to the mod's author here: https://github.com/illusivesoulworks/veinmining/issues/66
Hopefully we can get it resolved soon.

**Comment by AzureDoom** [comment]
Thanks for the follow up!

**Comment by AzureDoom** [comment]
Alright, this is good to close now, https://github.com/illusivesoulworks/veinmining/issues/66 is marked as fixed and the new release is working great with Prism and the latest Tooltips!

**Comment by AHilyard** [comment]
Wonderful news! 😄

**Comment by nau-tia** [comment]
Updating vein miner worked for me as well, thanks!
