### ISSUE TITLE
Double tooltips

### ISSUE THREAD

**Issue by Aethamus** [AHilyard/LegendaryTooltips#40]
Tooltips appear twice when viewing any item from Enigmatic Legacy

Minecraft: 1.16.5
Forge: 36.2.34
Legendary Tooltips: 1.3.1
Enigmatic Legacy: 2.11.12

The issue has been reported to Enigmatic Legacy as well by someone else

![2tooltips](https://user-images.githubusercontent.com/113189984/194111235-47aaccfb-dfbb-4087-b866-9f7595721a21.png)

**Comment by AHilyard** [comment]
Probably related to https://github.com/AHilyard/LegendaryTooltips/issues/29.  Unfortunately Enigmatic Legacy is handling tooltips in a non-standard way so it's going to be difficult to fix from my side.

**Comment by AHilyard** [comment]
This has been fixed in Enigmatic Legacy 2.25.
