### ISSUE TITLE
Caught error loading resourcepacks, removing all selected resourcepacks

### ISSUE THREAD

**Issue by GuerreroBit** [AHilyard/LegendaryTooltips#41]
When I join to minecraft (Join, exit and join for second time) (or add, remove, add the resourcepack (sometime it crash)) with the EclecticTrove, it unselect all resourcepacks. That only happen with EclecticTrove and I have 9 different resourcepacks (I tested one by one).
Tested resourcepacks:
![image](https://user-images.githubusercontent.com/30746531/194757522-773fa21e-301e-400f-8110-ff7b23102c3e.png)

And other thing I tried is try find if some mod is incompatible, and when I remove the "dashloader-4.1.3+1.19", apparently it doesn't have the error (Tried only about 2 or 3 times), but when I tried it only with LegendaryTooltips and DashLoader, I couldn't reproduce it.

Log (line 1198): https://gist.github.com/GuerreroBit/9f8ed5a20b54ce5d3bbf6198ec46e6be#file-gistfile1-txt-L1198
(Only when it have Stackoverflow, produce the error)

**Comment by GuerreroBit** [comment]
I have done more tests and it seems that the better-X mod (better nether, end or eden ring with the bclib) is also needed to "crash" the resource packs, but again, it couldn't be reproduced when only use these mods.

**Comment by GuerreroBit** [comment]
Sorry, apparently it has nothing to do with the EclecticTrove and it was just a coincidence that no other pack caused the error. (Yesterday I removed the resourcepack and today the error still occurs, so I guess it's some DashLoader or Indium bug)

**Comment by AHilyard** [comment]
> Sorry, apparently it has nothing to do with the EclecticTrove and it was just a coincidence that no other pack caused the error. (Yesterday I removed the resourcepack and today the error still occurs, so I guess it's some DashLoader or Indium bug)
Thank you for all your work looking into this.  I'm glad it's not Eclectic Trove causing the problem, hopefully Dashloader or Indium will be able to fix it quickly.
