### ISSUE TITLE
[1.19.2] Forge - Weird Conflict

### ISSUE THREAD

**Issue by Aulberon** [AHilyard/LegendaryTooltips#44]
I'm having some issues with Legendary Tooltips and Equipment Compare.
I'm not sure what's going on, but I believe it's a conflict with another mod, but I can't find which one.

Screenshot of the problem:
![2022-10-30_07 10 14](https://user-images.githubusercontent.com/39103311/198874485-ce0b2d21-2566-4864-881b-4b4905c995ed.png)

latest.log
[latest.log](https://github.com/AHilyard/LegendaryTooltips/files/9895689/latest.log)

ModList
[ModList.txt](https://github.com/AHilyard/LegendaryTooltips/files/9895691/ModList.txt)

**Comment by AHilyard** [comment]
This is a known issue with Majrusz Library, please see the relevant issue here: https://github.com/Majrusz/MajruszLibrary/issues/5
