### ISSUE TITLE
[1.12.2] Metadata support?

### ISSUE THREAD

**Issue by Turkey9002** [AHilyard/LegendaryTooltips#5]
Hey, thanks for this port first of all! I've been really enjoying it with my private modpack that I play around with and it was really splendid to customize items with it.

I wonder though if there's support for items that use metadata? I'm aware that this was ported from newer versions which had that removed. I tried adding a number at the end of the item name (i.e. minecraft:diamond_sword:2) to see if it did anything but it didn't seem to work. I wanted to ask this since the config doesn't mention anything about item metadata.

**Comment by AHilyard** [comment]
I know this is a long time coming, but I've released an update to Legendary Tooltips for 1.12.2 that includes metadata support.  You can get it here: https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips/files/4013371
