### ISSUE TITLE
[Small] Issue with PackedUp

### ISSUE THREAD

**Issue by xd4rkzghost01** [AHilyard/LegendaryTooltips#54]
Hi ! There a small issue with [PackedUp](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks) from  @SuperMartijn642 and because it's a display issue with LegendaryTooltips i might think you can check this out.
As you can see on the second screenshot, the item is completly out of line. Any idea how to fix that?

![NormalRender](https://user-images.githubusercontent.com/63568312/214333758-d064899a-c9b7-4b82-bc57-7b0c1280b1f9.png)
![OutscreenRender](https://user-images.githubusercontent.com/63568312/214333760-72c8cdb7-f9c4-4959-9c24-87d5ba37c9dc.png)

**Comment by AHilyard** [comment]
I've looked into this and found it is a bug in SuperMartijn642sCoreLib.  I've fixed the bug in that library and created a pull request, so the author is aware of it.

**Comment by SuperMartijn642** [comment]
Should be fixed now in version 1.1.1a of my core library.
Thanks for the help!

**Comment by AHilyard** [comment]
Wonderful news, thanks @SuperMartijn642!

**Comment by xd4rkzghost01** [comment]
Thx a lot for you two !!
