### ISSUE TITLE
hovering an armor or tool crashes the game 1.19.3

### ISSUE THREAD

**Issue by JeanYT1** [AHilyard/LegendaryTooltips#55]
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class com.anthonyhilyard.iceberg.renderer.VertexCollector$1 cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (com.anthonyhilyard.iceberg.renderer.VertexCollector$1 and me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6a396c1e)

**Comment by Caerum5** [comment]
Have the same

**Comment by AHilyard** [comment]
Thank you for the report, this issue is currently being tracked here: https://github.com/AHilyard/Iceberg/issues/21
I will close this issue, please follow the link for workarounds and more info.
