### ISSUE TITLE
[Bug] 1.18 fabric configuration failure 

### ISSUE THREAD

**Issue by Disxconected** [AHilyard/LegendaryTooltips#6]
[crash-2022-01-15_13.27.18-server.txt](https://github.com/AHilyard/LegendaryTooltips/files/7875621/crash-2022-01-15_13.27.18-server.txt)
[legendarytooltips-common.txt](https://github.com/AHilyard/LegendaryTooltips/files/7875625/legendarytooltips-common.txt)
Soo I'll try my best to summarize when attempting to use hexadecimal code to configure the border color of [client.colors] level10_start_color and level10_end_color the game crashed on launch and produced the attached crash log. after several attempts no noticeable change occurred. the only deviation was when standard decimal code was used and even then the configuration file reverted any change to the color codes higher then level 10 though in this instance the mod otherwise functioned normally

**Comment by AHilyard** [comment]
Unfortunately there is a strange bug in the underlying nightconfig library where hexadecimal numbers that contain the letter E or e will cause a crash.  I personally fixed this bug a few months ago here: https://github.com/TheElectronWill/night-config/pull/95
Unfortunately the change has not made it's way to the configuration mod I am using yet.  In the meantime, luckily you can still use hexadecimal numbers as strings in the format "#aecadf", so please use that instead.
