### ISSUE TITLE
Multiple display issues

### ISSUE THREAD

**Issue by robit4** [AHilyard/LegendaryTooltips#61]
I keep trying to rename my items with things like Dispenser or things like that (that make the tech background) on my items and it doesn't work like this
![2023-03-31_10 07 00](https://user-images.githubusercontent.com/126712560/229185218-ce79ee99-6363-4f44-b249-b89b9e92c138.png)
![2023-03-31_10 07 31](https://user-images.githubusercontent.com/126712560/229185319-6ed73052-0c0c-44b2-927d-1c4134daf29b.png)
Can it get fixed?

**Comment by AHilyard** [comment]
Hi there, I assume you are using the "noconfig" variant of Eclectic Trove, which does give the mechanical background to dispensers--but it is pre-configured to show for the dispenser item, not items with "Dispenser" in the name.  You can actually use the Legendary Tooltips config file to customize the behavior yourself, just find the line in the config file labeled "level7_entries" (the machinery border is border #7), and change it to this:

`level7_entries = ["%Dispenser"]`

I would also recommend you change your priorities line in the config file to this:

`priorities = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, -1]`

Which will make it so any changes you make in the config file will override Eclectic Trove's default border definitions.  The config file itself contains more instructions about how you can configure the mod.
