### ISSUE TITLE
hard crash when hovering

### ISSUE THREAD

**Issue by gonzome** [AHilyard/LegendaryTooltips#62]
anytime I put my cursor over a tool of any kind the game immediately crashes. I know it could be a mod, but I'm not sure which.

[crash-2023-04-06_02.00.10-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/11167263/crash-2023-04-06_02.00.10-client.txt)

**Comment by AHilyard** [comment]
I see that you are using Quilt, which has not been tested with my mods.  It looks like the crash is due to my use of VersionPredicateParser, which is part of Fabric's API which Quilt has not reimplemented.  I recommend you report this to Quilt so they can add this missing class.
