### ISSUE TITLE
Crash when hovering over any tool

### ISSUE THREAD

**Issue by AlfmanOO7** [AHilyard/LegendaryTooltips#64]
Minecraft opens fine and I can play normally until I hover over a tool in my inventory, which causes the game to crash instantly. Non-tool items seem to be fine (ie ones that do not show a 3D preview of the item) Attached are 4 crash reports all caused by Legendary Tooltips (or possibly iceberg, but it is definitely an interaction between the two mods are both are mentioned) each time a variable was changed (turning off CIT visual enchantments, using an older version of Forge Config API Port, updating Quilted Fabric)
[crash-2023-04-17_15.43.35-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/11246264/crash-2023-04-17_15.43.35-client.txt)
[crash-2023-04-17_15.30.45-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/11246265/crash-2023-04-17_15.30.45-client.txt)
[crash-2023-04-17_15.52.31-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/11246266/crash-2023-04-17_15.52.31-client.txt)
[crash-2023-04-17_15.47.52-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/11246263/crash-2023-04-17_15.47.52-client.txt)

**Comment by AlfmanOO7** [comment]
here is the full list of other mods I use if you suspect it may be caused by a conflict with one or more of them

3D Skin Layers	1.5.3
AdvancementsInfo	1.3.1
Ambient Sounds	5.2.18
Animatica	0.5.0
Appleskin	2.4.3
AuthMe	6.0.0
Auto Clicker	1.6.1
Better F3	6.0.0
Better Mount HUD	1.2.1
Blur	3.0.0
Bobby 	4.0.5
Borderless Mining	1.1.7
Camera Overhaul	1.4.0
Camera Utils	1.0.4
Chat Heads	0.10.9
Chat Patches	194.3.0
CITResewn	1.1.3
Cloth Config	10.0.96
Colour My Servers	1.0.3
Complete Config	2.3.1
Continue Button	1.0.7
CreativeCore	2.10.7
Dark Loading Screen	1.6.13
Do a Barrel Roll	2.7.0
Durability Notifier	1.5.0
Dynamic Crosshair	5.3.0
Dynamic Sound Filters	1.4.0
Eating Animation	1.9.3
EnhancedVisuals	1.6.4
Entity Model Features	0.2.5
Entity Texture Features	4.3.5
Fabric Carpet	1.4.101
Fabric Language Kotlin	1.9.2
Falling Leaves	1.15.0
FerriteCore	5.2.0
First Person Model	2.2.3
Indium	1.0.15
Inspecio	1.8.0
Inventory HUD+	3.4.11
Iris (Shaders)	1.6.0
Item Scroller	0.19.2
Item Swapper	0.4.0
Litematica	0.14.2
Lithium	0.11.1
Make Bubbles Pop	0.1.1
MaLiLib	0.15.3
Mambience	5.3.0
MemoryLeakFix	1.0.0
Minihud	0.26.2
Mod Menu	6.1.0 rc4
No Chat Reports	2.1.1
Not Enough Animations	1.6.3
Physics Mod	2.11.11
Presence Footsteps	1.8.0
Prism	1.0.4
Quilted Fabric API & Quilt Standard Libraries	6.0.0 Beta 3 & 5.0.0 Beta 2
Reese's Sodium Options	1.5.0
Replay Mod	2.6.12
Satin API	1.11.0
Simple Shulker Preview	2.3.1
Smooth Swapping	0.8.1
SmoothBoot	1.7.0
Sodium Extra	0.4.18
Sodium Fabric	0.4.10
Starlight	1.1.1
Stendhal	1.3.6
Tiny Item Animations	1.0.0
Tweakeroo	0.16.0
Visuality	0.7.0
Void Fog	2.9.0
Xaero's Minimap	23.4.0
Xaero's World Map	1.30.0
Yet Another Config Lib	2.3.1
Zoomify	2.9.4

**Comment by AHilyard** [comment]
Please see #62.  I don't currently support Quilt with my mods, since Quilt does not fully support the Fabric API that I am using.  Hopefully Quilt will add support for the API calls my mods use soon.

**Comment by LambdAurora** [comment]
This is actually not part of Fabric API but actually is an **implementation detail** of Fabric loader.
This is method call is **also** not supported by Fabric loader and may break at any time without warning.

Anything in an `impl` package is not public API.

**Comment by AlfmanOO7** [comment]
Didn't seem to fix it, seems to be crashing more or less the same, although it's now referencing sodium in the crash report (see attached). Thanks for trying to fix this so quickly, no worries if you guys can't fix this.
[crash-2023-04-18_07.07.33-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/11257934/crash-2023-04-18_07.07.33-client.txt)

**Comment by AHilyard** [comment]
> Didn't seem to fix it, seems to be crashing more or less the same, although it's now referencing sodium in the crash report (see attached). Thanks for trying to fix this so quickly, no worries if you guys can't fix this. [crash-2023-04-18_07.07.33-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/11257934/crash-2023-04-18_07.07.33-client.txt)

I should be able to fix this problem in the next Iceberg update, so look for version 1.1.9 soon.  However, keep in mind that I do not support Quilt with any of my mods, and after some choice messaging from a Quilt developer I no longer plan to.  My mods are not marked as Quilt-compatible on CurseForge nor Modrinth for that reason.

**Comment by LambdAurora** [comment]
> and after some choice messaging from a Quilt developer I no longer plan to.

What?
I have merely stated that the usage of Fabric internal methods are not supported either by Fabric nor Quilt, and such methods can break at any time on Fabric too. This was a good faith warning, I was in no case aggressive, just informative.
