### ISSUE TITLE
Crash when moving the mouse over a tool (1.19.4)

### ISSUE THREAD

**Issue by Caerum5** [AHilyard/LegendaryTooltips#65]
My game crashes when I try to hover my mouse over a (Netherite) tool or armor.

Crash Report: 
[crash-2023-04-17_13.29.42-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/11252593/crash-2023-04-17_13.29.42-client.txt)

**Comment by AHilyard** [comment]
Sorry, my mods do not support Quilt right now.
