### ISSUE TITLE
(RENDERING ISSUE) Always crashing when hovering over any tool/armor/weapon

### ISSUE THREAD

**Issue by deltaloni** [AHilyard/LegendaryTooltips#71]
MC Version: 1.19.4
Legendary Tooltips Version: 1.4.3 & 1.4.2 (tried both)
Iceberg Version 1.1.10
Sodium Version: 0.4.10+

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-05-16 17:03:23
Description: Rendering item

java.lang.ClassCastException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:641)

-- Item being rendered --
Details:
	Item Type: netherite_sword
	Registry Name: minecraft:netherite_sword
	Item Damage: 0
	Item NBT: {Damage:0}
	Item Foil: false
Stacktrace:
	at com.anthonyhilyard.iceberg.renderer.CustomItemRenderer.renderDetailModelIntoGUI(CustomItemRenderer.java:641)
	at com.anthonyhilyard.legendarytooltips.tooltip.ItemModelComponent.drawItems(ItemModelComponent.java:111)
	at MC//net.minecraft.client.gui.screen.Screen.renderTooltipFromComponents(Screen.java:325)
	at MC//net.minecraft.client.gui.screen.Screen.renderTooltip(Screen.java:245)
	at MC//net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.renderTooltip(CreativeInventoryScreen.java:777)
	at MC//net.minecraft.client.gui.screen.ingame.HandledScreen.drawMouseoverTooltip(HandledScreen.java:179)
	at MC//net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.render(CreativeInventoryScreen.java:743)
	at MC//net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:121)
	at MC//net.minecraft.client.render.GameRenderer.render(GameRenderer.java:937)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1218)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (491, 219). Absolute: (983.000000, 438.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['Darkahrii'/111, l='ClientLevel', x=-1131.79, y=59.00, z=-236.41]]
	Chunk stats: 1024, 609
	Level dimension: minecraft:the_end
	Level spawn location: World: (20,63,-48), Section: (at 4,15,0 in 1,3,-3; chunk contains blocks 16,0,-48 to 31,255,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 53923 game time, 53923 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	(removed)

	Fabric Mods: 
		ambientsounds: Ambient Sounds (Fabric) 5.2.19
		appleskin: AppleSkin 2.4.3+mc1.19.4
		architectury: Architectury 8.1.80
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		creativecore: CreativeCore (Fabric) 2.10.12
			net_minecraftforge_eventbus: eventbus 6.0.4
		eatinganimationid: Eating Animation 1.9.3
		equipmentcompare: Equipment Compare 1.3.6
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
		fabric-api: Fabric API 0.81.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.26+1e9487d2f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.27+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.36+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.17+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.29+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.8+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.46+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.56+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.11+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.0+c98e6b27f4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.2+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.47+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.15+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.1+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.54+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.19+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.7+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.17+1e9487d2f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.29+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.33+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.3+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.41+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.32+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.3+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.43+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.5+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.25+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.10+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.2+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.7+ebc93ff3f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.2.0+ebc93ff3f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.40+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.30+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.23+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.43+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.3+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.4+5ade3c38f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.47+3bd4ab0ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.22+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.0+80d07a0af4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.1.0+03ba59cef4
		fabricloader: Fabric Loader 0.14.19
		firstperson: FirstpersonModel 2.2.3
		forgeconfigapiport: Forge Config API Port 6.0.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		iceberg: Iceberg 1.1.10
		indium: Indium 1.0.15+mc1.19.4
		invmove: InvMove 0.8.3
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.7
			journeymap-api-fabric: JourneyMap API 1.19.4-1.9-fabric-SNAPSHOT
		legendarytooltips: Legendary Tooltips 1.4.3
		litematica: Litematica 0.14.2
		lithium: Lithium 0.11.1
		make_bubbles_pop: Make Bubbles Pop Mod 0.1.1-1.19.4
		malilib: MaLiLib 0.15.4
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.2.2
		mousewheelie: Mouse Wheelie 1.10.7+mc1.19.4
			amecsapi: Amecs API 1.3.9+mc1.19.4
			coat: Coat 1.0.0-beta.19+mc1.19.4
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.19.4
			tweed4_base: tweed4_base 1.7.1+mc1.19.4
			tweed4_data: tweed4_data 1.2.1+mc1.19.4
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.19.4
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.19.4
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.19.4
		notenoughanimations: NotEnoughAnimations 1.6.3
		phosphor: Phosphor 0.8.1
		presencefootsteps: Presence Footsteps 1.8.0
			kirin: Kirin UI 1.14.0
		prism: Prism 1.0.4
		roughlyenoughitems: Roughly Enough Items 11.0.597
			error_notifier: Error Notifier 1.0.9
		skinlayers: 3d Skin Layers 1.5.3-mc1.19.4
		sodium: Sodium 0.4.10+build.24
		stackdeobfuscator: StackDeobfuscator 1.3.2+fabric.4bca927
			net_fabricmc_mapping-io: mapping-io 0.3.0
		wi_zoom: WI Zoom 1.4-MC1.19.4
		yet_another_config_lib: YetAnotherConfigLib 2.5.1+1.19.4
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: en_us
	CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Darkahrii'/111, l='ServerLevel[WISMP Test World]', x=-1131.79, y=59.00, z=-236.41]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by Noidea699** [comment]
managed to solve?

**Comment by AHilyard** [comment]
Sorry for the inconvenience, what you are experiencing is an incompatibility between version 1.1.10 of Iceberg and Sodium version 0.4.10. Version 1.1.10 of Iceberg was designed for version 0.4.11 of Sodium, but that version has been removed.

Version 1.1.10 of Iceberg for Fabric has now been archived, so please downgrade Iceberg to an older version to fix this issue.
