### ISSUE TITLE
After activating Legendary Tooltips again, Chests are upside down.

### ISSUE THREAD

**Issue by RosivDamotil** [AHilyard/LegendaryTooltips#74]
I tested it.
With legendary Tooltips, the chests are upside down (single chests).
Without the chests paper normal.

I have no clue why and can't explain, but legendary tooltips was the only mod I disabled because of the iceberg bug.

**Comment by RosivDamotil** [comment]
Guess it's not a Bug from Legendary Tooltips.
Maybe Iceberg did change something but with another texture pack (haven't changed anything) the chests behave normal.

Pretty confusing and strange.... Maybe because the texture pack WOULD overwrite the chests skin, but can't as I don't have OptiFine. But this would be a great coincidence that your change in Iceberg triggered that...

**Comment by AHilyard** [comment]
I have been unable to recreate this issue, and I don't really see how it's possible unless you are talking about the 3D item preview perhaps?  In any case, I am closing this but if you can provide screenshots / a way to recreate it myself you can reopen.
