### ISSUE TITLE
Crash with Quark after updating Quark to latest.

### ISSUE THREAD

**Issue by Darkmega18** [AHilyard/LegendaryTooltips#75]
I had a bundle, and I was putting it into my sophisticated backpack after filling it up with an assortment of different drops and such things from mobs while exploring. I held shift on it for a split second and it crashed after transferring it.

LegendaryTooltips-1.19.2-forge-1.4.0.jar
Quark-3.4-401.jar

**Crash report:**
[crash-2023-05-24_19.41.53-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/11553039/crash-2023-05-24_19.41.53-client.txt)

**Comment by AHilyard** [comment]
I believe this crash has been fixed in Quark 402.  I will close this issue, but feel free to reopen if Quark 402 does not fix it.

**Comment by Darkmega18** [comment]
ok. I'll go check it soon.
