### ISSUE TITLE
Please update to Minecraft version 1.20 for your mod.

### ISSUE THREAD

**Issue by surfishs** [AHilyard/LegendaryTooltips#81]
Please update to Minecraft version 1.20 for your mod.

**Comment by OBS3SS1ON** [comment]
x2 I need 1.20.1 ♥♥ 🥇 :(

**Comment by ccrowles** [comment]
Seconded specifically for 1.20 (since 1.20.1 is already available), Iceberg just got updated for 1.20 so it would be nice to see this mod updated for that version too.

**Comment by AHilyard** [comment]
You will all be happy to hear that Legendary Tooltips version 1.4.4 has been released which supports both 1.20 and 1.20.1. 😄

**Comment by ccrowles** [comment]
Thank you!
