### ISSUE TITLE
[1.20.1] Crash upon opening creative inventory tab

### ISSUE THREAD

**Issue by MrKashew** [AHilyard/LegendaryTooltips#85]
[crash-2023-07-11_14.36.56-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/12021683/crash-2023-07-11_14.36.56-client.txt)

**Comment by PooPooSkin** [comment]
I'm having a similar issue, it seems to happen when you hover over any tool or armor, which from what I know all have the 3D spinning image in the tooltip

[crash-2023-07-16_02.40.04-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/12063491/crash-2023-07-16_02.40.04-client.txt)

**Comment by Brayman4k** [comment]
same issue here

**Comment by AHilyard** [comment]
Thank you for the report, this has been fixed in the latest update to Iceberg (1.1.12).
