### ISSUE TITLE
Crashes the second I hover over vanilla tools, but if hovering over modded stuff, doesn't crash at all

### ISSUE THREAD

**Issue by NewAgeSoldier** [AHilyard/LegendaryTooltips#86]
Basically this is what I am left with from the launcher : The game crashed whilst rendering item
Error: java.lang.ClassCastException: class com.anthonyhilyard.iceberg.renderer.VertexCollector$1 cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (com.anthonyhilyard.iceberg.renderer.VertexCollector$1 is in module iceberg@1.1.10 of loader 'TRANSFORMER' @708769b7; me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter is in module rubidium@0.6.5 of loader 'TRANSFORMER' @708769b7) 

Crash Log will be attached to this post as well
[latest.log](https://github.com/AHilyard/LegendaryTooltips/files/12024058/latest.log)

So yeah, hope this helps :) Not sure why this happened at all, but to add, while looking in the resource packs section, it says it is not compatible at all.. I will hold off from using this mod and a couple of others until that is fixed :)

**Comment by yustier** [comment]
This does not resolve the problem completely but setting the value `render_item_model` to `"NONE"` in the config file `legendarytooltips-common.toml` prevented those crashes (although now the rotating models of tools and armours don't show)

The top of stacktrace mentions vertex something so I suspected this has something to do with rendering the rotating item icon. Hope that helps while being fixed.

**Comment by NewAgeSoldier** [comment]
I will attempt this, I will firstly attempt to put it on ALL... See if it does something different for my client, as my pack is very much custom (barely touched any configs so I can hardly call it custom), but.... The tooltip works fine with Create, Mekanism and other mods, just the base game it crashes on which is very strange to me... From here I will give you the results of  each setting :

All : Crash on vanilla
Some : Crash on vanilla
None : Functional... Interesting

To add : I am using Rubidium, it has caused some funkyness with Mekanism as well, Meka Suit turns the player completely invisible if shaders are active, perhaps Rubidium is doing something here as well. Just a thought

**Comment by NewAgeSoldier** [comment]
![image](https://github.com/AHilyard/LegendaryTooltips/assets/10442785/ac9bb27f-b8e0-48b1-9437-9d1148a2d9a9)


Perhaps it has something to do with another tooltip mod I have?

**Comment by NewAgeSoldier** [comment]
Here is also the latest crash with all set on, just so you can use it for debug :)

[latest.log](https://github.com/AHilyard/LegendaryTooltips/files/12044274/latest.log)

**Comment by PooPooSkin** [comment]
I am also having a similar issue as well, here's my crash report

[crash-2023-07-16_02.40.04-client.txt](https://github.com/AHilyard/LegendaryTooltips/files/12063501/crash-2023-07-16_02.40.04-client.txt)

**Comment by AHilyard** [comment]
Those of you using Forge, please try updating to Iceberg 1.1.12.  I believe it should fix this crash.

**Comment by NewAgeSoldier** [comment]
> Those of you using Forge, please try updating to Iceberg 1.1.12. I believe it should fix this crash.

I will attempt so... Cause if that is the main cause of it... I may just stick to that version, but as the Forge version is currently 47.1.28, I will see if anything happens from there

**Comment by NewAgeSoldier** [comment]
![image](https://github.com/AHilyard/LegendaryTooltips/assets/10442785/e5b78b02-7fad-461e-aebb-1caecba0acdf)
To notify you upon Iceberg : This may be a little Curse moment

**Comment by NewAgeSoldier** [comment]
![image](https://github.com/AHilyard/LegendaryTooltips/assets/10442785/aff47f86-c1a2-432f-ac92-52672b67ef8a)
It has indeed fixed this issue :) 👍

**Comment by AHilyard** [comment]
Great, thank you for verifying.  I have done additional testing and I believe this is resolved.
