### ISSUE TITLE
Mod detected as a Trojan...

### ISSUE THREAD

**Issue by ItzNatsu** [AHilyard/LegendaryTooltips#89]
Windows Defender detected the mod as a trojan as soon as i tried zipping it.

![image](https://github.com/AHilyard/LegendaryTooltips/assets/68730384/18025999-431f-4151-9e4a-46a8811cb789)

**Comment by AHilyard** [comment]
Where did you download this from?  I'd like to check it out myself, since it appears to have been tampered with.

**Comment by AHilyard** [comment]
Thank you for the report, as discussed in Discord I have submitted the file to Microsoft as a false positive.  Hopefully this will stop being detected with the next definitions update.
