### ISSUE TITLE
[Compatibility] [Fabric] Tooltip borders are not shown in REI

### ISSUE THREAD

**Issue by teleheel** [AHilyard/LegendaryTooltips#9]
Is it possible to add compatibility such that the tooltip borders are correctly displayed in the REI screen?

**Comment by AHilyard** [comment]
Yes, I will look into this to see if it's possible.  I know that REI is doing tooltips in a non-standard way, so I will likely have to write a plugin to get it working.

**Comment by SpigotDE** [comment]
This would be awesome <3

**Comment by gabriel-andreescu** [comment]
Any news about this? Maybe this will help https://github.com/shedaniel/RoughlyEnoughItems/issues/645

**Comment by AHilyard** [comment]
Sorry for the delay in updating this issue, this has been implemented since Legendary Tooltips version 1.2.6.
