### ISSUE TITLE
No tooltips show up at all when mod is loaded.

### ISSUE THREAD

**Issue by IgorPomidor** [AHilyard/LegendaryTooltips#91]
I don't use any other mods that add new items or blocks, just vanilla items. Aside from that I only use Optifine, Appleskin, AmbientSounds 5 and Sound Physics Remastered.

The tooltips just do not show up at all, doesn't matter what item it is, none show up. Help?

**Comment by AHilyard** [comment]
Thanks for the report, this has been fixed in the latest version of Iceberg/Legendary Tooltips.
