### ISSUE TITLE
1.20.1, when paired with oculus and rubidum the game will crash

### ISSUE THREAD

**Issue by NinjaAlexaIsNotAvailable** [AHilyard/LegendaryTooltips#92]
1.20.1 , when playing with oculus and/or rubidium on forge the game will always crash when opening your inventory , i removed every single one of my mods one by one and it kept crashing , until i removed oculus and rubidium.
After testing a little i found out it will not crash unless you have an item which has a 3d model display appear when you hover your mouse over it , things like armour pieces , swords and weapons , as long as you have an item which has a 3d model shown when you hover over it in your inventory your game will crash the moment you open it

**Comment by AHilyard** [comment]
I have just released an update to Iceberg (1.1.12) that should fix this crash.  Please reopen if you continue to experience issues.
