### ISSUE TITLE
I'm sorry but what? They didn't need an update and this randomly happened???

### ISSUE THREAD

**Issue by NewAgeSoldier** [AHilyard/LegendaryTooltips#96]
Mod ID: 'iceberg', Requested by: 'legendarytooltips', Expected range: '[1.1.10,)', Actual version: '[MISSING]'
Mod ID: 'iceberg', Requested by: 'advancementplaques', Expected range: '[1.1.10,)', Actual version: '[MISSING]'

I honestly have no idea

**Comment by NewAgeSoldier** [comment]
I had it installed yes, for some reason it fixed itself today... Still not entirely sure why this occured, I seem to have different problems with different mods.... It is as if the mods just forgot there was a library there....


AE2 is currently sticking to 47.1.3 Forge, which sucks cause now most mods will be out of date before they get up to date... 

Optifine won't even let my game start if I install that, and Rubidium has major conflicts with every mod in existence.... So many weird things these days for mods

**Comment by AHilyard** [comment]
If I understand correctly, your issue has been resolved so I will close this ticket.  If you are still having this issue feel free to reopen.
